"""Initial migrations

Revision ID: 91d1eebd532b
Revises: 
Create Date: 2023-06-01 18:58:32.354604

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '91d1eebd532b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'users',
        sa.Column('username', sa.String(length=128), nullable=False),
        sa.Column('hashed_pass', sa.String(length=256), nullable=False),
        sa.Column('phone', sa.String(length=16), nullable=False),
        sa.Column('phone_hash', sa.String(length=256), nullable=True),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=True)
    op.create_table(
        'pics',
        sa.Column('filename', sa.String(length=256), nullable=False),
        sa.Column('timezone', sa.String(length=6), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ['user_id'],
            ['users.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_pics_id'), 'pics', ['id'], unique=True)
    op.create_index(op.f('ix_pics_user_id'), 'pics', ['user_id'], unique=False)
    op.create_table(
        'schedules',
        sa.Column('days_of_week', sa.String(length=7), nullable=False),
        sa.Column('day_time', sa.String(length=7), nullable=False),
        sa.Column('pic_id', sa.UUID(), nullable=False),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ['pic_id'],
            ['pics.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_schedules_id'), 'schedules', ['id'], unique=True)
    op.create_index(op.f('ix_schedules_pic_id'), 'schedules', ['pic_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_schedules_pic_id'), table_name='schedules')
    op.drop_index(op.f('ix_schedules_id'), table_name='schedules')
    op.drop_table('schedules')
    op.drop_index(op.f('ix_pics_user_id'), table_name='pics')
    op.drop_index(op.f('ix_pics_id'), table_name='pics')
    op.drop_table('pics')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
